### ISSUE TITLE
script doesn't work.

### ISSUE THREAD

**Issue by jadedgnome** [OffensivePython/Proxist#2]
Traceback (most recent call last):
  File "proxist.py", line 248, in <module>
    main()
  File "proxist.py", line 231, in main
    country=querryInfo(html, "country")
  File "proxist.py", line 124, in querryInfo
    result=re.search('alt="flag" /> (.+)</span>', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by wgmueller1** [comment]
I get the same error.

**Comment by OffensivePython** [comment]
a new version will be released soon

**Comment by OffensivePython** [comment]
the new version is here
https://github.com/OffensivePython/Proxist/blob/master/proxist.py
